### ISSUE TITLE
Behaviour when comparator returns NaN

### ISSUE THREAD

**Issue by missinglink** [Two-Screen/stable#14]
In the case where the comparator returns `NaN` (such as `(A,B) => B-A` where either, or both, are `undefined`) the behaviour of this lib differs from that of vanilla JS:

```bash
console.error([1, 2, 3].sort(() => NaN))
console.error(stable.inplace([1, 2, 3], () => NaN))
[ 1, 2, 3 ]
[ 3, 2, 1 ]
```

```bash
console.error([3, 2, 1].sort(() => NaN))
console.error(stable.inplace([3, 2, 1], () => NaN))
[ 3, 2, 1 ]
[ 1, 2, 3 ]
```

It's really the fault of the comparator function since it should only return a finite number, but in the case where it doesn't, I would argue that it's preferable to treat `NaN` as `0`, so as to not affect the order.

It's unfortunately an easy mistake to make, such as when sorting numerically:

```
(A, B) => B - A
```

If either of the values is `undefined` (or both!) it triggers this issue.

**Comment by stephank** [comment]
I'm considering archiving this project. As of ES2019, the language builtin array `sort` is guaranteed stable, so there's very little benefit to using this library.

What do you think? Do you still have some use for it?

**Comment by stephank** [comment]
Great! I've added the notice, and will be archiving the repo now. Thanks! 👍
