### ISSUE TITLE
Feature Request: multiple sort parameters

### ISSUE THREAD

**Issue by dodtsair** [Two-Screen/stable#4]
A stable sort is nice because you can sort it over and over again by the same criteria to get nested sort orders.  

My question, would it be faster to also enable multiple levels of comparator and run the sort once.  The alternative would be to sort and resort with each comparator.  

Option 1, multiple levels of comparators

```
stable.inplace(array, [byName, byValue, byId])
```

vs Options 2, multiple sorts

```
stable.inplace(array, byId);
stable.inplace(array, byValue);
stable.inplace(array, byName);
```

Also would be nice to sort by fields with writing the sort function:
    stable.inplace(array, "id");
    stable.inplace(array, "value");
    stable.inplace(array, "name");

**Comment by stephank** [comment]
I *think* something like this should work as well:

```javascript
stable.inplace(array, function(a, b) {
  return byId(a, b) || byValue(a, b) || byName(a, b);
});
```

**Comment by stephank** [comment]
Hey, if you're still using this, please note I'm archiving this repository. Modern engines already have stable sort, so you should be able to drop the dependency. 🙂
